# Generated by Django 5.0.6 on 2025-02-28 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile', models.FileField(blank=True, null=True, upload_to='company_profile')),
                ('products_and_services', models.FileField(blank=True, null=True, upload_to='product_services')),
                ('policies', models.FileField(blank=True, null=True, upload_to='company_policies')),
                ('chatbot_color', models.CharField(default='#ffffff', max_length=7)),
                ('g_api', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
