# Generated by Django 5.0.6 on 2025-02-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_data_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_profile',
            name='policies_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_data_profile',
            name='products_and_services_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_data_profile',
            name='profile_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
