# Generated by Django 5.0.6 on 2025-03-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_data_profile_policies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data_profile',
            name='bot_name',
            field=models.CharField(default='AI-Bot', max_length=30),
        ),
    ]
